version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - vendor:/go/src/api/vendor
    ports:
      - 3001:3001
    tty:
      true
    depends_on:
      - db
  db:
    image: mysql:5.7.26
    container_name: godockerDB
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - gin_data:/var/lib/mysql

volumes:
  gin_data:
  vendor:
